name: Test 

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: wearerequired/lint-action@v1
        with:
          node-version: [16.x]
      - run: npm ci
      - run: npm run lint